version: "2.1"
services:
  dynuiuc:
    image: ghcr.io/go2engle/dynuiuc:1.1
    container_name: dynuiuc
    environment:
      - USERNAME=Your_username
      - PASSWORD=Your_password
    restart: unless-stopped
